#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# border
bspc config normal_border_color \#665c54
bspc config active_border_color \#928374
bspc config focused_border_color \#fe8019

# single window in workspace
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle true

# autostart
sxhkd &
picom --config ~/.config/picom/picom.conf --experimental-backends &
feh --bg-fill ~/Pictures/gruvboxdebian.png &
polybar &
dunst &
